import crypto from 'crypto';
import type { BrandIdentity, BrandVoice, ImageStyle, ImageAspectRatio, ImageProvider } from '@/lib/schemas';
import { fetchWithRetry } from '@/lib/fetch-retry';

export type ImageGenRequest = {
  prompt: string;
  brandIdentity?: BrandIdentity;
  brandVoice?: BrandVoice;
  productName?: string;
  style: ImageStyle;
  aspectRatio: ImageAspectRatio;
  provider: ImageProvider;
};

export type ImageGenResult = {
  imageUrl: string;
  provider: ImageProvider;
  revisedPrompt?: string;
};

/**
 * Build a prompt that incorporates brand identity and produces studio-quality images.
 */
function buildBrandedPrompt(req: ImageGenRequest): string {
  const parts: string[] = [];

  // Style instruction with studio-quality photography direction
  const styleMap: Record<ImageStyle, string> = {
    photorealistic: 'Shot on iPhone 17 Pro Max, 48MP main camera, ProRAW. Ultra-realistic photograph with natural lighting, shallow depth of field, cinematic color grading. Studio-quality editorial image',
    illustration: 'Premium digital illustration with rich detail, professional-grade vector art quality, vibrant colors, clean composition',
    minimal: 'Clean minimalist design, elegant negative space, precise typography-friendly layout, premium aesthetic with subtle gradients',
    abstract: 'High-end abstract composition with sophisticated color palette, artistic textures, dynamic visual flow, gallery-quality',
    branded: 'Professional commercial photography, studio lighting setup, product-shot quality, advertising-grade image with premium feel',
  };
  parts.push(styleMap[req.style] || styleMap.branded);

  // Main prompt
  parts.push(`depicting: ${req.prompt}.`);

  // Product name
  if (req.productName) {
    parts.push(`This is marketing content for "${req.productName}".`);
  }

  // Brand colors
  if (req.brandIdentity) {
    const colors: string[] = [];
    if (req.brandIdentity.primaryColor) colors.push(`primary color ${req.brandIdentity.primaryColor}`);
    if (req.brandIdentity.secondaryColor) colors.push(`secondary color ${req.brandIdentity.secondaryColor}`);
    if (req.brandIdentity.accentColor) colors.push(`accent color ${req.brandIdentity.accentColor}`);
    if (colors.length > 0) {
      parts.push(`Incorporate the brand color palette: ${colors.join(', ')}.`);
    }
  }

  // Brand voice tone
  if (req.brandVoice?.tone) {
    parts.push(`The visual mood should convey a ${req.brandVoice.tone} feeling.`);
  }

  // Quality boosters
  parts.push('8K resolution, sharp focus, professional color correction, social media ready, high dynamic range, no artifacts, no watermarks.');

  return parts.join(' ');
}

/**
 * Generate image using Gemini 3.1 Flash (Nano Banana 2) — native image generation.
 */
async function generateWithGemini(prompt: string, _aspectRatio: ImageAspectRatio): Promise<{ base64: string; mimeType: string }> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('GEMINI_API_KEY is not configured');

  const response = await fetchWithRetry(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent?key=${apiKey}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          responseModalities: ['TEXT', 'IMAGE'],
        },
      }),
    },
  );

  const data = await response.json();

  if (!response.ok) {
    throw new Error(`Gemini API error: ${data.error?.message || JSON.stringify(data)}`);
  }

  const parts = data.candidates?.[0]?.content?.parts;
  if (!parts) {
    throw new Error('No content in Gemini response');
  }

  const imagePart = parts.find((p: { inlineData?: { mimeType: string; data: string } }) => p.inlineData);
  if (!imagePart?.inlineData) {
    throw new Error('No image generated by Gemini');
  }

  return {
    base64: imagePart.inlineData.data,
    mimeType: imagePart.inlineData.mimeType || 'image/png',
  };
}

/**
 * Generate image using OpenAI DALL-E 3.
 */
async function generateWithOpenAI(prompt: string, aspectRatio: ImageAspectRatio): Promise<{ base64: string; mimeType: string; revisedPrompt?: string }> {
  const OpenAI = (await import('openai')).default;
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY is not configured');

  const openai = new OpenAI({ apiKey });

  // Map aspect ratios to DALL-E sizes
  const sizeMap: Record<ImageAspectRatio, '1024x1024' | '1792x1024' | '1024x1792'> = {
    '1:1': '1024x1024',
    '16:9': '1792x1024',
    '9:16': '1024x1792',
    '4:5': '1024x1024',
  };

  const response = await openai.images.generate({
    model: 'dall-e-3',
    prompt,
    n: 1,
    size: sizeMap[aspectRatio],
    response_format: 'url',
    quality: 'hd',
  });

  const imageData = response.data?.[0];
  if (!imageData?.url) {
    throw new Error('No image URL in OpenAI response');
  }

  const imgRes = await fetchWithRetry(imageData.url);
  if (!imgRes.ok) throw new Error('Failed to download image from OpenAI');
  const buffer = Buffer.from(await imgRes.arrayBuffer());

  return {
    base64: buffer.toString('base64'),
    mimeType: 'image/png',
    revisedPrompt: imageData.revised_prompt ?? undefined,
  };
}

/**
 * Upload base64 image to Firebase Storage and return a signed URL.
 */
async function uploadToFirebaseStorage(
  base64: string,
  mimeType: string,
  workspaceId: string,
): Promise<string> {
  const admin = await import('firebase-admin');
  const bucket = admin.storage().bucket();

  const fileId = crypto.randomUUID();
  const ext = mimeType.includes('png') ? 'png' : 'jpg';
  const filePath = `workspaces/${workspaceId}/generated/${fileId}.${ext}`;
  const file = bucket.file(filePath);

  const buffer = Buffer.from(base64, 'base64');

  await file.save(buffer, {
    metadata: {
      contentType: mimeType,
      metadata: {
        workspaceId,
        generatedAt: new Date().toISOString(),
      },
    },
  });

  // Make the file publicly readable and return a direct URL
  await file.makePublic();
  const bucketName = bucket.name;
  return `https://storage.googleapis.com/${bucketName}/${filePath}`;
}

/**
 * Generate an image using the specified provider, with fallback.
 * Tries Gemini 3.1 Flash (Nano Banana 2) first, falls back to OpenAI DALL-E 3.
 */
export async function generateImage(req: ImageGenRequest): Promise<{ base64: string; mimeType: string; provider: ImageProvider; revisedPrompt?: string }> {
  const prompt = buildBrandedPrompt(req);

  if (req.provider === 'gemini') {
    try {
      const result = await generateWithGemini(prompt, req.aspectRatio);
      return { ...result, provider: 'gemini' };
    } catch (e) {
      console.error('Gemini image generation failed, falling back to OpenAI:', e);
    }
  }

  // OpenAI (primary or fallback)
  const result = await generateWithOpenAI(prompt, req.aspectRatio);
  return {
    base64: result.base64,
    mimeType: result.mimeType,
    provider: 'openai',
    revisedPrompt: result.revisedPrompt,
  };
}

/**
 * Full pipeline: generate image + upload to Firebase Storage.
 */
export async function generateAndUploadImage(
  req: ImageGenRequest,
  workspaceId: string,
): Promise<ImageGenResult> {
  const result = await generateImage(req);
  const imageUrl = await uploadToFirebaseStorage(result.base64, result.mimeType, workspaceId);

  return {
    imageUrl,
    provider: result.provider,
    revisedPrompt: result.revisedPrompt,
  };
}
